export const TAG_REQUEST_ROUTE = 'api/tagrequest';
export const ENV_VAR_NAMES = {
  PORT: 'PORT',
  RABBITMQ_URI: 'RABBITMQ_URI',
  DB_UPDATE_EXCHANGE_NAME: 'DB_UPDATE_EXCHANGE_NAME',
  TAG_ADDITION_QUEUE_NAME: 'TAG_ADDITION_QUEUE_NAME',
  TAG_REMOVAL_QUEUE_NAME: 'TAG_REMOVAL_QUEUE_NAME',
  TAG_ADDITION_QUEUE_ROUTING_KEY: 'TAG_ADDITION_QUEUE_ROUTING_KEY',
  TAG_REMOVAL_QUEUE_ROUTING_KEY: 'TAG_REMOVAL_QUEUE_ROUTING_KEY',
  DEFAULT_TAGS_CACHE_KEYS_TTL_SECONDS: 'DEFAULT_TAGS_CACHE_KEYS_TTL_SECONDS',
};
