apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.containers.main.name }}
          image: "{{ .Values.containers.main.image.repository }}:{{ .Values.containers.main.image.tag }}"
          ports:
            - containerPort: {{ .Values.containers.main.port }}
          env:
            {{- range $key, $value := $.Values.containers.main.envVars }}
            - name: {{ $value.name }}
              value: {{ $value.value | quote}}
            {{- end}}
          volumeMounts:
            - name: config-{{ .Values.name }}-volume-mount
              mountPath: /config/configmaps/
      volumes:
        - name: config-{{ .Values.name }}-volume-mount
          configMap:
            name: {{ .Values.name }}-configmap
