/**
 * user-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface DataSource {
  /**
   * Data source name
   */
  name: string;
  /**
   * Data source URL host
   */
  host: string;
  /**
   * Path array to the resource
   */
  resourcePath: Array<string>;
  /**
   * Query parameters array
   */
  _queryParameters: Array<string>;
  /**
   * Values for the query parameters
   */
  queryValues: Array<string>;
  /**
   * Access token for the API
   */
  accessToken: string;
  /**
   * Resource path for access token refresh
   */
  refreshTokenResourcePath: Array<string>;
  /**
   * Query parameters for refresh token API
   */
  refreshTokenQueryParameters: Array<string>;
  /**
   * Values for refresh token query parameters
   */
  refreshTokenQueryValues: Array<string>;
}
