name: Pull Request Pipeline

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Build services
      run: ./infra/.build-linux/build.sh
    - name: Docker build:item-tagger-service
      env:
        IMAGE_NAME: '${{env.DOCKER_HUB_REPO_NAME}}/${{env.IMAGE_PREFIX}}${{env.ITEM_TAGGER_SERVICE_NAME}}:master-latest'
        IMAGE_PATH: 'apps/${{env.ITEM_TAGGER_SERVICE_NAME}}/Dockerfile'
      run: docker build --progress=plain --no-cache -t $IMAGE_NAME -f $IMAGE_PATH .
    
